$tomcat_gratia doesn't have to exist for new installs; it's doing an mkdir -p further down anyway.
Sleep not necessary since init script now blocks until shutdown.

Add documentation.

Fail on bad exit code from configure-collector.


git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk@1749 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/common/configuration/update-gratia-local b/common/configuration/update-gratia-local
--- a/common/configuration/update-gratia-local
+++ b/common/configuration/update-gratia-local
@@ -4,7 +4,8 @@
 function usage() {
 cat 1>&2 <<EOF
 usage: update-gratia-local [-S <source-prefix>] [-j <jre-home>] [-s] \
-                           [-p <prefix>] [-d <db-root-pw>] 
+                           [-p <prefix>] [-d <db-root-pw>] \
+                           [-c <configure-collector-script>] \
                            [-h] [-v <vdt_location>] [--] <instance>
 
        -c <configure-collector-script>
@@ -71,7 +72,6 @@ function stop_tomcat {
     if [ -e /etc/init.d/$init_service ];then
       echo "... stopping tomcat ($init_service)"
       service $init_service stop 2>/dev/null
-      sleep 5
     else
       echo "... $init_service is already stopped"
     fi
@@ -141,8 +141,7 @@ for dir in $source_prefix \
            $configuration_dir \
            $tomcat_root \
            $target_dir \
-           $tomcat_webapps \
-           $tomcat_gratia
+           $tomcat_webapps
 do
   echo "... checking $dir"
   if [ ! -d $dir ]; then
@@ -245,6 +244,11 @@ $use_ssl \
 -j "$java_jre" \
 $dbp_arg "$dbpwd" \
 $instance
+status=$?
+  if (( $status != 0 )); then
+    echo "ERROR: configure-collector invocation returned non-zero exit code $status." 1>&2
+    exit $status
+  fi 
 fi 
 ls -l ${tomcat_webapps}
 
