Soften the check for the webapps directory if install-tomcat is specified.
git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk@3687 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/common/configuration/update-gratia-local b/common/configuration/update-gratia-local
--- a/common/configuration/update-gratia-local
+++ b/common/configuration/update-gratia-local
@@ -379,8 +379,7 @@ configuration_dir=$source_prefix/common/configuration
 for dir in $source_prefix \
            $configuration_dir \
            $tomcat_root \
-           $target_dir \
-           $tomcat_webapps
+           $target_dir
 do
   echo "... checking $dir"
   if [ ! -d $dir ]; then
@@ -389,6 +388,10 @@ do
   fi
 done
 
+if (( ! ${install_tomcat:-0} )) && [ ! -d "$tomcat_webapps" ]; then
+  echo "ERROR: Unable to find specified directory $tomcat_webapps and --install-tomcat not specified." 1>&2
+  exit 1
+fi
 
 #-----------------------
 # Check for java
