Added verification of java and mysql client availability.
git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk@2292 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/common/configuration/update-gratia-local b/common/configuration/update-gratia-local
--- a/common/configuration/update-gratia-local
+++ b/common/configuration/update-gratia-local
@@ -207,6 +207,25 @@ do
   fi
 done
 
+#-----------------------
+# Check for java
+#-----------------------
+echo "... checking for java"
+if [ "$(type java >/dev/null 2>&1;echo $?)" ];then
+  if [ ! -x $java_jre/bin/java ];then
+    echo;echo "ERROR: Cannot find java ($java_jre/bin/java)";echo
+    exit 1
+  fi
+fi
+#-----------------------
+# Check for mysql
+#-----------------------
+echo "... checking for mysql"
+if [ "$(type mysql >/dev/null 2>&1;echo $?)" != "0" ];then
+  echo;echo "ERROR: Cannot find mysql client on this node";echo
+  exit 1
+fi
+
 
 #-----------------------
 # Stop tomcat
