Split re-usable parts of install-nightly-builds into install-group scriptlet
git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk@3938 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/build-scripts/install-nightly-builds b/build-scripts/install-nightly-builds
--- a/build-scripts/install-nightly-builds
+++ b/build-scripts/install-nightly-builds
@@ -16,6 +16,20 @@
 ########################################################################
 prog=${0##*/}
 
+####################################
+# Required function do_installs
+function do_installs() {
+  for c in nightly_{batch,psacct,osg_daily}; do
+    printf "########################################################################\n"
+    "${INSTALL_SCRIPT}" -t -p -a \
+                        "$VERSION_OPT" "$VERSION_ARG" \
+                         -C "${CONFIG_DIR}/collector-nightly.dat" \
+                         -m "$MAILTO" \
+                         -c "${c}"
+  done
+}
+####################################
+
 # Install-related variables.
 VERSION_OPT="-B"
 VERSION_ARG=latest
@@ -24,146 +38,13 @@ INSTALL_SCRIPT=${SCRIPT_TOPDIR}/build-scripts/install-release
 CONFIG_DIR=${SCRIPT_TOPDIR}/common/configuration
 MAILTO=gratia-builds@fnal.gov
 
-########################################################################
-# Functions
-########################################################################
-
-####################################
-# usage
-function usage() {
-    cat 1>&2 <<EOF
-usage: $prog --help|-h|\?
-       $prog [<options>]
-
-Options:
-
-   -h
-   -\?
-  --help
-    This help.
-
-   -m <mailto>
-  --mail <mailto>
-    Change destination for mailed reports.
-
-   -d
-  --debug
-    Output is copied to screen in addition to being mailed.
-
-   -v
-  --verbose
-
-    Under normal circumstances, the report for each install will be sent
-    under separate cover; any standard output from this script is
-    suppressed and only standard error will be sent to the specified
-    recipient. If --verbose is specified, then standard output from this
-    script will not be suppressed.
-
-EOF
-}
-####################################
-
-####################################
-# cleanup
-#
-# Clean up and exit, making sure we preserve and send output.
-####################################
-function cleanup() {
-  [[ -n "$TMP" ]] || return # Nothing to do
-  # Restore output and close file
-  if [[ -f "$TMP.log" ]]; then
-    exec 4>&2 1>&3-
-    # If we have non-zero output, send it.
-    if [[ -s "$TMP.log" ]]; then
-      subject="REPORT from install-nightly-builds on `hostname -s`"
-      mutt -F "$TMP.muttrc" -s "$subject" "$MAILTO" <"$TMP.log" >/dev/null 2>&1
-    fi
-    (( ${debug:-0} )) && cat "$TMP.log"
-  fi
-  # Clean up.
-  rm "$TMP*" 2>/dev/null
-}
-####################################
-
-####################################
-# do_installs
-#
-# Actually do the installs. Separated to allow easy redirect of output.
-####################################
-function do_installs() {
-  service=nbuild
-  for INSTANCE in nightly_{batch,psacct,osg_daily}; do
-    printf "########################################################################\n"
-    "${INSTALL_SCRIPT}" -t -p -a \
-                        "$VERSION_OPT" "$VERSION_ARG" \
-                         -C "${CONFIG_DIR}/collector-${service}.dat" \
-                         -c "$INSTANCE" -m "$MAILTO"
-  done
-}
-####################################
-
-########################################################################
-# Main program.
-####################################
-TMP=`mktemp ${TMPDIR:-/tmp}/install-nightly-builds.XXXXXXXXXX`
-trap "cleanup" EXIT
-
-# Send mail with output from this script.
-cat > $TMP.muttrc <<EOF
-set realname = "Gratia nightly builds"
-set from = "gratia-builds@fnal.gov"
-EOF
-
-# Redirect output to file and trap exit.
-exec 3>&1 4>&2 >"$TMP.log" 2>&1
-trap "cleanup" EXIT # Need to re-do trap after exit.
-
 # Handle build retries.
 (( max_retries = 5 ))
 (( retry = 0 ))
 
-####################################
-# Parse options, including long options.
-TEMP=`getopt -o :dh\?v -n "$prog" --long debug --long verbose --long mail: --long help -- "$@"`
-
-if [ $? != 0 ]; then
-  echo "terminating due to option parse errors" 1>&2
+if [[ ! -r "${SCRIPT_TOPDIR}" ]]; then
+  echo "ERROR: specified script top directory \"${SCRIPT_TOPDIR}\"" 1>&2
   exit 1
-fi
-
-eval set -- "$TEMP"
-
-while true; do
-    case $1 in
-      -d|--debug)
-        debug=1
-        shift
-        ;;
-      --help|-h|-\?)
-        usage
-        exit 1
-        ;;
-      --mail)
-        MAILTO=$2
-        shift 2
-        ;;
-      -v|--verbose)
-        verbose=1
-        shift
-        ;;
-      --)
-        shift
-        break
-        ;;
-      *)
-    esac
-done
-####################################
-
-# If we're running this script as root, get the host credentials.
-if (( $(id -u) == 0 )); then
-  export KRB5CCNAME=$TMP.krb5
-  /usr/krb5/bin/kinit -k
 fi
 
 # Make sure the build is actually ready to be used.
@@ -179,7 +60,8 @@ if (( retry > max_retries )); then # failed
   exit 1
 fi
 
-# Install all required collectors.
-(( ${verbose:-0} )) || redirect=">/dev/null"
+########################################################################
+# Main program.
+####################################
 
-eval do_installs "$redirect"
+. ~gratia/gratia-builds/gratia-latest/install-group "$@"
